### ISSUE TITLE
Node edit view seems to be broken if coming to it from the back button.

### ISSUE THREAD

**Issue by alexbrinkman** [pushtype/push_type#15]
If I'm on a edit node view, click to go to the media library (for example), then click the back button, the edit node view seems to load fine, but the save button doesn't work, nor do any of the wysiwyg toolbar buttons.  If I refresh the page, it's fine again.  It's only when landing on the edit page from the back button.

I've tried on Chrome and Firefox to the same effect.

Perhaps a turbolinks issue?

**Comment by aaronrussell** [comment]
Thanks - yes, the combination of turbolinks, Vue.js and Foundation does create a few problems. I'll take a look.

**Comment by aaronrussell** [comment]
This was caused due to Turbolinks caching - when going back Vue was throwing an error when initialising on the cached DOM. Short term solution to disable caching on Turbolinks (see 9715cc4). Long term solution to move away from Turbolinks and to more of a pure JavaScript SPA.

Thanks for reporting this. Will try and get a new release out tomorrow.

**Comment by alexbrinkman** [comment]
Thanks for being so responsive, I'm glad it was an easy fix!
